name: Dependabot Auto-Approve

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  pull-requests: write
  contents: write
  packages: write

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Merge Dependabot PR
        uses: ahmadnassri/action-dependabot-auto-merge@v2.6.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
